version: '3.7'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: shop_marry
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: student_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://shop_marry:123@db:5432/student_db
    command: pytest

volumes:
  postgres_data:
