# XPath locators

SIGN_IN_BUTTON = "//button[contains(@class, 'btn-outline-white') and contains(@class, 'header_signin') and text()='Sign In']"
EMAIL_FIELD = "//input[@name='email' and @type='text']"
PASSWORD_FIELD = "//input[@name='password' and @type='password']"
LOGIN_BUTTON = "//button[text()='Login']"
XPATH_GUEST_LOGIN = "//button[contains(@class, 'header-link--guest') and contains(text(), 'Guest log in')]"
XPATH_HERO_SECTION_TITLE = "//h1[contains(@class, 'hero-descriptor_title') and text()='Do more!']"
XPATH_FOOTER_SUPPORT_LINK = "//footer//a[@href='mailto:support@ithillel.ua']"
XPATH_ADD_EXPENSE_BUTTON = "//button[contains(@class, 'btn') and text()='Add an expense']"
XPATH_FUEL_EXPENSES_ROW = "//table[@class='fuel-expenses']//tr[position()>1]"
XPATH_FIRST_EXPENSE_DATE = "//table[@class='fuel-expenses']//tr[2]/td[1]"
XPATH_CAR_MANUAL_LINK = "//div[@id='instructions']//a[contains(@href, 'instructions')]"
XPATH_CONTACT_SECTION_HEADER = "//div[@id='contactSection']//h2[contains(text(), 'Contacts')]"
XPATH_SEARCH_BUTTON = "//button[@type='submit' and text()='Search']"
XPATH_SELECT_CAR = "//select[@name='car']"
XPATH_YOUTUBE_IFRAME = "//iframe[contains(@src, 'youtube')]"
XPATH_INSTRUCTION_LINK = "//div[contains(@class, 'content')]//a[contains(@href, 'manual')]"
XPATH_BACK_TO_TOP = "//a[contains(@class, 'back-to-top') and text()='Back to top']"
XPATH_SECOND_EXPENSE_ROW = "//table[@class='fuel-expenses']//tr[3]"
XPATH_SEARCH_FIELD = "//input[@name='search']"
XPATH_SORT_BUTTON = "//button[contains(@class, 'sort-button') and @aria-label='Sort']"
XPATH_VIEW_MORE_BUTTON = "//button[contains(text(), 'View more')]"
XPATH_DOWNLOAD_BUTTON = "//a[contains(text(), 'Download')]"
XPATH_FOOTER_SOCIAL_LINKS = "//footer//a[contains(@class, 'social-link')]"

XPATH_HEADER_LOGO = "//header//img[@alt='Hillel Auto Logo']"
XPATH_LOGIN_FORM = "//form[@id='LoginForm']"
XPATH_CHECKBOX_REMEMBER_ME = "//input[@type='checkbox' and @name='remember']"

# CSS locators
CSS_SIGN_IN_BUTTON = "button.btn-outline-white.header_signin"
CSS_EMAIL_FIELD = "input[name='email'][type='text']"
CSS_PASSWORD_FIELD = "input[name='password'][type='password']"
CSS_LOGIN_BUTTON = "button:contains('Login')"
CSS_GUEST_LOGIN = "a:contains('Guest log in')"
CSS_HERO_SECTION_TITLE = "h1:contains('Do more!')"
CSS_FOOTER_SUPPORT_LINK = "footer a[href='mailto:support@ithillel.ua']"
CSS_ADD_EXPENSE_BUTTON = "button.btn:contains('Add an expense')"
CSS_FUEL_EXPENSES_ROW = "table.fuel-expenses tr:nth-of-type(n+2)"  # Вибір від другого рядка таблиці
CSS_FIRST_EXPENSE_DATE = "table.fuel-expenses tr:nth-of-type(2) td:first-child"
CSS_CAR_MANUAL_LINK = "div.instructions a[href*='manual']"
CSS_CONTACT_SECTION_HEADER = "div#contactSection h2:contains('Contacts')"
CSS_SEARCH_BUTTON = "button[type='submit'][value='Search']"
CSS_SELECT_CAR = "select[name='car']"
CSS_YOUTUBE_IFRAME = "iframe[src*='youtube']"
CSS_INSTRUCTION_LINK = "div.content a[href*='manual']"
CSS_BACK_TO_TOP = "a.back-to-top:contains('Back to top')"
CSS_SECOND_EXPENSE_ROW = "table.fuel-expenses tr:nth-of-type(3)"
CSS_SEARCH_FIELD = "input[name='search']"
CSS_SORT_BUTTON = "button.sort-button[aria-label='Sort']"
CSS_VIEW_MORE_BUTTON = "button:contains('View more')"
CSS_DOWNLOAD_BUTTON = "a:contains('Download')"
CSS_FOOTER_SOCIAL_LINKS = "footer a.social-link"
CSS_HEADER_LOGO = "header img[alt='Hillel Auto Logo']"
CSS_LOGIN_FORM = "form#LoginForm"
CSS_CHECKBOX_REMEMBER_ME = "input[type='checkbox'][name='remember']"

